name: Playwright Tests with Sauce Labs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name my-node-app my-node-app

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting... ($i)"
            sleep 5
          done
          echo "Server did not start in time"
          docker logs my-node-app
          exit 1

      - name: Run Playwright tests
        run: |
          echo "Running Playwright tests..."
          docker exec my-node-app sh -c "npx playwright test"
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: Upload Playwright results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: /usr/src/app/playwright-report

      - name: Stop and remove Docker container
        if: always()
        run: |
          echo "Stopping and removing Docker container..."
          docker stop my-node-app
          docker rm my-node-app
